@startuml
!include C4_Context.puml

Person(user, "Пользователь", "Пользователь системы")
Person(supporter, "Технический специалист", "Производит подключение систем отопления к системе")

System(warm_house, "Система Теплый дом", "Позволяет управлять системой отопления и отслеживать температуру с датчиков")

System_Ext(heat_system, "Система отопления дома", "Отапливает дом")

Rel(user, warm_house, "Управление отоплением")
Rel(warm_house, heat_system, "Взаимодействие с датчиками")
Rel(supporter, heat_system, "Подключение к системе Теплый дом", "Ручное подключение")
@enduml